project:
  type: website
  output-dir: docs
  
website:
  title: "Contents"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Portfolio
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/brendan-callender-4569a7218/
      - icon: github
        href: https://github.com/brendad8/website
      - icon: envelope
        href: mailto:bren.call8@gmail.com
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc: true

editor: source

# morph, cosmo. spacelab